homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
	path('play/', views.play, name='play'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')
	
def play(request):
	return render(request, 'play.html')

homepage/templates/challenge.html
<body>
<div style="width:100vw">
	<a href="http://www.w3schools.com/w3css/">powered by w3.css</a>
</div>
</body>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Welcome! | Ivan Taftazani's</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<!--CSS FILES REQUIRED-->
		<link type="text/css" rel="stylesheet" href="{% static 'w3.css' %}">
		<link type="text/css" rel="stylesheet" href="{% static 'custom.css' %}"/>	
		<link type="text/css" rel="stylesheet" href="{% static 'aos.css' %}"/>

		<style>
			.main {
				background-size: cover;
				background-attachment: fixed;
				background-image: url("{% static "bnw-balairung2.jpg" %}");
				overflow: hidden;
			}
		</style>
		
	</head>
	
	<body>
		<div class="main">
			<!-- row 1 -->
			<div id="home" class="w3-row w3-black welcome-row w3-display-container">
				<img class="w3-display-middle" src="{% static 'balloon-bg.png' %}" style="width: 100vw; max-height: 100vh">
				<img class="wiggle navbar-opener-side" onclick="openNavSide()" src="{% static 'small-arrow.png' %}" id="buttonside">
				<img class="wiggle navbar-opener-top" onclick="openNavTop()" src="{% static 'small-arrow-down.png' %}" id="buttontop">
				<div id="top navbar" class="navbar-top">
					<a href="javascript:void(0)" onclick="closeNavTop()"><img class="closebtn" src="{% static 'cross.png' %}" style="max-width:20px"></a>
					<a href="#section1">About me</a>
					<a href="#section2">Contact me</a>
					<a href="{% url 'homepage:play' %}">Let's play</a>
				</div>
				<div id="side navbar" class="navbar-side">
					<a href="javascript:void(0)" onclick="closeNavSide()"><img class="closebtn" src="{% static 'cross.png' %}" style="max-width:20px"></a>
					<a href="#section1">About me</a>
					<a href="#section2">Contact me</a>
					<a href="{% url 'homepage:play' %}">Let's play</a>
				</div>
			</div>
			
			<!-- row 2 -->
			<div id="section1" class="w3-row profile-row">
				<!-- col 1 -->
				<div data-aos="slide-right" data-aos-duration=1000 class="w3-third w3-display-container col1">
					<div class="w3-display-topmiddle">
						<center>
							<img src="{% static 'portraitsmaller2.png' %}" style="margin-top: 8vh">
							<hr>
							<h1> ivan taftazani</h1>
							<h2>of<h2>
							<h3>University of Indonesia<h3>
							<hr>
							<h3>1  8  0  6  2  4  1  1  2  2<h3>
						</center>
					</div>
				</div>
				<!-- col 2 -->
				<div data-aos="slide-left" data-aos-duration=1000 class="w3-twothird w3-display-container col2" style="padding: 4vh 4vw">
					<h1><b>"Play hard, work hard"</b></h1>
					<br/>
					<p style="margin: 0 0 10vh">
						The words I live by. Though much more biased towards the former rather than the latter, the fact
						stays that mantaining the balance between the two has been the principle I'm holding on for the most of the 2 decades I've been living.
					</p>
					
					<img style="max-height:4vh; float:left; margin: 0 1vw" src="{% static 'ui-logo.png' %}" alt="ui small logo">
					<h3 style="font-family:Impact"> Faculty of Computer Science (2018)	</h3>
					<hr style="opacity:0">
					<img style="max-height:4vh; float:left; margin: 0 1vw" src="{% static 'yellowheart.png' %}" alt="ui small logo">
					<h3 style="font-family:Impact"> Video games, Golf</h3>
					
					<div class="w3-display-bottommiddle w3-center" style="margin-bottom: 3vw"> 
						<center>
							<h1> Skills </h1>
							<img title="PYTHON" src="{% static 'python-logo.png' %}" alt="python">
							<img title="JAVA" src="{% static 'java-logo.png' %}" alt="java">
							<img title="C++" src="{% static 'cpp-logo-bl.png' %}" alt="c++">
							<img title="HTML5" src="{% static 'html5-logo2.png' %}" alt="html5">
							<img title="CSS3" src="{% static 'css3-logo.png' %}" alt="css3">
						</center>
					</div>
				</div>
			</div>
			
			<!-- row 3 -->
			<div id="section2" class="w3-row contact-row w3-display-container">
				<!-- col 1 -->
				<div data-aos="slide-right" data-aos-duration=1000 class="w3-half col1">
					<center><h1><b> Let's get in touch... </b></h1></center>
					<br/><br/><br/><br/>
					<img src="{% static 'location-logo.png' %}" alt="location">
					<h3> Duren Sawit, Jakarta Timur</h3>
					<br/><br/>
					<img src="{% static 'phone.png' %}" alt="phone">
					<h3> 0821 642 398 28</h3>
					<br/><br/>
					<img src="{% static 'mail.png' %}" alt="mail">
					<h3>muhammad.ivan83@ui.ac.id</h3>
				</div>
				
				<!-- col 2 -->
				<div data-aos="slide-left" data-aos-duration=1000 class="w3-half col2">
					<center>
						<h1><b> ...or play with me! </b></h1>
						<br/><br/><br/>
						<a href="{% url 'homepage:play' %}"><img src="{% static 'steam-logo.png' %}" alt="steam logo"></a>
					</center>
				</div>
			</div>
			
			{ % include 'challenge.html' % }
			
			<div class="socmed">
				<center>
				<a href="https://www.instagram.com/ivantft/"><img style="max-height:3vh;" src="{% static 'ig-logo.png' %}" alt="instagram"></a>
				<a href="https://twitter.com/IvanTFT"><img style="max-height:3vh;" src="{% static 'twitter-logo.png' %}" alt="twitter"></a>
				<a href="http://line.me/ti/p/~vntft"><img style="max-height:3vh;" src="{% static 'line-logo.png' %}" alt="line"></a>
				<a href="https://www.facebook.com/ipuntft"><img style="max-height:3vh;" src="{% static 'facebook-logo.png' %}" alt="facebook"></a>
				<!--
				<a href="https://steamcommunity.com/profiles/76561198124884164"><img style="max-height:50px; padding:10px 5px; max-width: 7%" src="img/steam-logo.png" alt="steam"></a>
				-->
				</center>
			</div>
		</div>
		
		<!-- javascript -->
		<script>
			function openNavTop() {
				document.getElementById("top navbar").style.height = "4vh";
				document.getElementById("buttontop").style.opacity = "0";
			}

			function closeNavTop() {
				document.getElementById("top navbar").style.height = "0";
				document.getElementById("buttontop").style.opacity= "1";
			}
		</script>
		<script>
			function openNavSide() {
				document.getElementById("side navbar").style.width = "250px";
				document.getElementById("buttonside").style.opacity = "0";
			}

			function closeNavSide() {
				document.getElementById("side navbar").style.width = "0";
				document.getElementById("buttonside").style.opacity= "1";
			}
		</script>
		<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
		<script src="{% static 'aos.js' %}"></script>
		<script> AOS.init(); </script>
	</body>

homepage/templates/play.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Play with me!</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link type="text/css" rel="stylesheet" href="{% static 'w3.css' %}">
		<link type="text/css" rel="stylesheet" href="{% static 'custom2.css' %}"/>	
		<link type="text/css" rel="stylesheet" href="{% static 'aos.css' %}"/>
		<style>
			.main {
				padding-top: 5vh;
				background-size: cover;
				background-attachment: fixed;
				background-image: url("{% static "steam-bg.png" %}");
				overflow: hidden;
			}
			
		</style>


	</head>	
	
	<body>
		<img class="wiggle navbar-opener-side" onclick="openNavSide()" src="{% static 'small-arrow.png' %}" id="buttonside">
		<img class="wiggle navbar-opener-top" onclick="openNavTop()" src="{% static 'small-arrow-down.png' %}" id="buttontop">
		<div class="main">
			<div id="top navbar" class="navbar-top">
				<a href="javascript:void(0)" onclick="closeNavTop()"><img class="closebtn" src="{% static 'cross.png' %}" style="max-width:20px"></a>
				<a href="{% url 'homepage:index' %}">Home</a>
				<a href="#">Let's play</a>
			</div>
			<div id="side navbar" class="navbar-side">
				<a href="javascript:void(0)" onclick="closeNavSide()"><img class="closebtn" src="{% static 'cross.png' %}" style="max-width:20px"></a>
				<a href="{% url 'homepage:index' %}">Home</a>
				<a href="#">Let's play</a>
			</div>
			<br/>
			<center><h1><b> Let's play together</b></h1></center>
			<br/><br/><br/><br/>
			<table class="w3-table w3-centered">
				<tr>
					<td><img src="{% static 'mhw-logo.png' %}"></td>
					<td><img src="{% static 'dota-logo.png' %}"></td>
					<td><img src="{% static 'csgo-logo.png' %}"></td>
					<td><img src="{% static 'pubg-logo.png' %}"></td>
				<tr>
					<td><img src="{% static 'mk11-logo.png' %}"></td>
					<td><img src="{% static 'tekken-logo.png' %}"></td>
					<td><img src="{% static 'smash-logo.png' %}"></td>
					<td><img src="{% static 'mk8-logo.png' %}"></td>
				</tr>
				<tr></tr>
				<tr>
					<td></td>
					<td><a href="https://steamcommunity.com/profiles/76561198124884164"><img src="{% static 'steam-logo-blue.png' %}"></a></td>
					<td><img title="SW-3739-6003-8314" src="{% static 'switch-logo.png' %}"></td>
					<td></td>
				</tr>
			
			
		</table>
		
		<script>
			function openNavTop() {
				document.getElementById("top navbar").style.height = "4vh";
				document.getElementById("buttontop").style.opacity = "0";
			}

			function closeNavTop() {
				document.getElementById("top navbar").style.height = "0";
				document.getElementById("buttontop").style.opacity= "1";
			}
		</script>
		<script>
			function openNavSide() {
				document.getElementById("side navbar").style.width = "250px";
				document.getElementById("buttonside").style.opacity = "0";
			}

			function closeNavSide() {
				document.getElementById("side navbar").style.width = "0";
				document.getElementById("buttonside").style.opacity= "1";
			}
		</script>
	</body>
</html>